name: Translations

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - dev
    paths:
      - "**strings.json"
      - ".github/workflows/translations.yaml"

env:
  DEFAULT_PYTHON: 3.9

jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check for secrets.LOKALISE_TOKEN
        shell: bash
        run: |
          if [ -n "${{ secrets.LOKALISE_TOKEN }}" ]; then
            echo "::set-output name=lokalise::1"
          fi

  upload:
    name: Upload
    needs: secrets
    if: needs.secrets.outputs.lokalise
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upload Translations
        run: |
          export LOKALISE_TOKEN="${{ secrets.LOKALISE_TOKEN }}"
          python3 -m script.translations upload

  download:
    name: Download
    needs: upload
    if: (needs.secrets.outputs.lokalise) && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Download Translations
        run: |
          export LOKALISE_TOKEN="${{ secrets.LOKALISE_TOKEN }}"
          python3 -m script.translations download

      - name: Initialize git
        uses: home-assistant/actions/helpers/git-init@master
        with:
          name: GitHub Action
          email: github-action@users.noreply.github.com

      - name: Update translation
        run: |
          git add homeassistant
          git commit -am "[ci skip] Translation update"
          git push
